// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEdMOkgN9k8fqOkTu4tUzk4eFbQLKZpU',
    appId: '1:523803108804:web:2811c0f2a50d800f5d3091',
    messagingSenderId: '523803108804',
    projectId: 'smartparkingapp-b59d5',
    authDomain: 'smartparkingapp-b59d5.firebaseapp.com',
    databaseURL: 'https://smartparkingapp-b59d5-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingapp-b59d5.firebasestorage.app',
    measurementId: 'G-MQ1BMJ1VQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrvIjuK53U6_FJqpwHgkqCoAM_NvWNOA',
    appId: '1:523803108804:android:5cd45c5878b810ca5d3091',
    messagingSenderId: '523803108804',
    projectId: 'smartparkingapp-b59d5',
    databaseURL: 'https://smartparkingapp-b59d5-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingapp-b59d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdPXsVXBabvykiT5GgHoQJeN0-vMfcH4',
    appId: '1:523803108804:ios:13a0f6bd587d43895d3091',
    messagingSenderId: '523803108804',
    projectId: 'smartparkingapp-b59d5',
    databaseURL: 'https://smartparkingapp-b59d5-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingapp-b59d5.firebasestorage.app',
    iosBundleId: 'com.example.park',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdPXsVXBabvykiT5GgHoQJeN0-vMfcH4',
    appId: '1:523803108804:ios:13a0f6bd587d43895d3091',
    messagingSenderId: '523803108804',
    projectId: 'smartparkingapp-b59d5',
    databaseURL: 'https://smartparkingapp-b59d5-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingapp-b59d5.firebasestorage.app',
    iosBundleId: 'com.example.park',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiEdMOkgN9k8fqOkTu4tUzk4eFbQLKZpU',
    appId: '1:523803108804:web:51d3f1fafd844b6a5d3091',
    messagingSenderId: '523803108804',
    projectId: 'smartparkingapp-b59d5',
    authDomain: 'smartparkingapp-b59d5.firebaseapp.com',
    databaseURL: 'https://smartparkingapp-b59d5-default-rtdb.firebaseio.com',
    storageBucket: 'smartparkingapp-b59d5.firebasestorage.app',
    measurementId: 'G-C1DGXB9FZK',
  );

}